---
- name: Deploy configuration file
  become: yes
  template:
    src: artifactory_configuration.j2
    dest: "{{ JFROG_home_directory }}/var/etc/potato.yml"
    owner: artifactory
    group: artifactory