---
- name: Deploy configuration file
  template:
    src: artifactory_configuration.j2
    dest: "{{ JFROG_home_directory }}/var/etc/potato.yml"
    owner: artifactory
    group: artifactory

- name: Echo file contents
  command: "cat {{ JFROG_home_directory|quote }}/var/etc/potato.yml"