---
- name: Install the dirmngr
  apt:
    name: dirmngr
    state: present
- name: Retrieve GPG Key
  apt_key:
    keyserver: "{{ artifactory_apt_key }}"
    id: "{{ artifactory_apt_key_id }}"
    state: present
- name: Add Apt repository
  apt_repository:
    repo: "deb {{ artifactory_apt_repo }} {{ ansible_distribution_release }} main"
    state: present
